cc_library(
    name = "stm32f429xx_startup",
    srcs = [
        "gcc/startup_stm32f429xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)

filegroup(
    name = "stm32f4xx_system_srcs",
    srcs = [
        "system_stm32f4xx.c",
    ],
    visibility=["//visibility:public"]
)

