cc_library(
    name = "stm32f401xc_startup",
    srcs = [
        "gcc/startup_stm32f401xc.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f401xe_startup",
    srcs = [
        "gcc/startup_stm32f401xe.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f405xx_startup",
    srcs = [
        "gcc/startup_stm32f405xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f407xx_startup",
    srcs = [
        "gcc/startup_stm32f407xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f410cx_startup",
    srcs = [
        "gcc/startup_stm32f410cx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f410rx_startup",
    srcs = [
        "gcc/startup_stm32f410rx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f410tx_startup",
    srcs = [
        "gcc/startup_stm32f410tx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f411xe_startup",
    srcs = [
        "gcc/startup_stm32f411xe.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f412cx_startup",
    srcs = [
        "gcc/startup_stm32f412cx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f412rx_startup",
    srcs = [
        "gcc/startup_stm32f412rx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f412vx_startup",
    srcs = [
        "gcc/startup_stm32f412vx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f412zx_startup",
    srcs = [
        "gcc/startup_stm32f412zx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f413xx_startup",
    srcs = [
        "gcc/startup_stm32f413xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f415xx_startup",
    srcs = [
        "gcc/startup_stm32f415xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f417xx_startup",
    srcs = [
        "gcc/startup_stm32f417xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f423xx_startup",
    srcs = [
        "gcc/startup_stm32f423xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f427xx_startup",
    srcs = [
        "gcc/startup_stm32f427xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f429xx_startup",
    srcs = [
        "gcc/startup_stm32f429xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f437xx_startup",
    srcs = [
        "gcc/startup_stm32f437xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f439xx_startup",
    srcs = [
        "gcc/startup_stm32f439xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f446xx_startup",
    srcs = [
        "gcc/startup_stm32f446xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f469xx_startup",
    srcs = [
        "gcc/startup_stm32f469xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


cc_library(
    name = "stm32f479xx_startup",
    srcs = [
        "gcc/startup_stm32f479xx.s",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"]
)


filegroup(
    name = "stm32f4xx_system_srcs",
    srcs = [
        "system_stm32f4xx.c",
    ],
    visibility=["//visibility:public"]
)

