filegroup(
	name = "stm32_usb_device_core_sources",
	srcs = [
		"Inc/usbd_core.h",
		"Inc/usbd_ctlreq.h",
		"Inc/usbd_def.h",
		"Inc/usbd_ioreq.h",
		"Src/usbd_core.c",
		"Src/usbd_ctlreq.c",
		"Src/usbd_ioreq.c",
	],
	visibility=["//visibility:public"],
)