cc_library(
    name = "cmsis_includes",
    hdrs = [
        "arm_common_tables.h",
        "arm_const_structs.h",
        "arm_math.h",
        "cmsis_armcc.h",
        "cmsis_armcc_V6.h",
        "cmsis_gcc.h",
        "core_cm0.h",
        "core_cm0plus.h",
        "core_cm3.h",
        "core_cm4.h",
        "core_cm7.h",
        "core_cmFunc.h",
        "core_cmInstr.h",
        "core_cmSimd.h",
        "core_sc000.h",
        "core_sc300.h",
    ],
    visibility = ["//visibility:public"],
)

