#!/bin/bash --norc

PATH="external/com_arm_developer_toolchain_gcc_6_2/libexec/gcc/arm-none-eabi/6.2.1:$PATH" \
    exec \
    external/com_arm_developer_toolchain_gcc_6_2/bin/arm-none-eabi-gcc \
    "$@"
